<Project>
  <PropertyGroup>
    <QuickStacksVersion>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</QuickStacksVersion>
    <Version>$(QuickStacksVersion)</Version>
    <AssemblyVersion>$(QuickStacksVersion)</AssemblyVersion>
    <FileVersion>$(QuickStacksVersion)</FileVersion>
    <InformationalVersion>$(QuickStacksVersion)</InformationalVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
