<Project>
  <PropertyGroup>
    <QuickStacksVersion>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</QuickStacksVersion>
    <Version>$(QuickStacksVersion)</Version>
    <AssemblyVersion>$(QuickStacksVersion).0</AssemblyVersion>
    <FileVersion>$(QuickStacksVersion).0</FileVersion>
    <InformationalVersion>$(QuickStacksVersion)</InformationalVersion>
    <Authors>Alexandre Chaves</Authors>
    <Company>Alexandre Chaves</Company>
    <Product>QuickStacks</Product>
    <Copyright>Copyright © 2026 Alexandre Chaves</Copyright>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
